Re-organize the OSS workflows (#2209)
Summary:
- Re-organize the OSS workflows to de-duplicate jobs

Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/2209

Reviewed By: spcyppt

Differential Revision: D52102704

Pulled By: q10

fbshipit-source-id: 6eca3b0c05cdcfb80d06e9e2fad0a96b851d8879

diff --git a/.github/workflows/fbgemm_gpu_ci_cuda.yml b/.github/workflows/fbgemm_gpu_ci_cuda.yml
--- a/.github/workflows/fbgemm_gpu_ci_cuda.yml
+++ b/.github/workflows/fbgemm_gpu_ci_cuda.yml
@@ -3,9 +3,9 @@
 # This source code is licensed under the BSD-style license found in the
 # LICENSE file in the root directory of this source tree.
 
-# This workflow is used for both CI as well as nightly builds against
-# PyTorch-ROCm Nightly.
-name: FBGEMM_GPU-ROCm CI
+# This workflow is used for FBGEMM_GPU-CUDA CI as well as nightly builds of
+# FBGEMM_GPU-CUDA against PyTorch-CUDA Nightly.
+name: FBGEMM_GPU-CUDA CI
 
 on:
   # PR Trigger (enabled for regression checks and debugging)
@@ -48,7 +48,7 @@ jobs:
   build_artifact:
     runs-on: ${{ matrix.host-machine.instance }}
     container:
-      image: ${{ matrix.container-image }}
+      image: amazonlinux:2023
       options: --user root
     defaults:
       run:
@@ -56,22 +56,20 @@ jobs:
     env:
       PRELUDE: .github/scripts/setup_env.bash
       BUILD_ENV: build_binary
+    continue-on-error: true
     strategy:
+      # Don't fast-fail all the other builds if one of the them fails
       fail-fast: false
       matrix:
         host-machine: [
           { arch: x86, instance: "linux.24xlarge" },
         ]
-        container-image: [ "ubuntu:20.04" ]
         python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
-        rocm-version: [ "5.7" ]
+        cuda-version: [ "11.8.0", "12.1.1" ]
 
     steps:
     - name: Setup Build Container
-      run: |
-        apt update -y
-        apt install -y binutils git pciutils sudo wget
-        git config --global --add safe.directory '*'
+      run: yum update -y; yum install -y binutils findutils git pciutils sudo tar wget which
 
     - name: Checkout the Repository
       uses: actions/checkout@v4
@@ -84,17 +82,11 @@ jobs:
     - name: Display GPU Info
       run: . $PRELUDE; print_gpu_info
 
-    - name: Free Disk Space
-      run: . $PRELUDE; free_disk_space
-
     - name: Setup Miniconda
       run: . $PRELUDE; setup_miniconda $HOME/miniconda
 
     - name: Create Conda Environment
       run: . $PRELUDE; create_conda_environment $BUILD_ENV ${{ matrix.python-version }}
-
-    - name: Install ROCm
-      run: . $PRELUDE; install_rocm_ubuntu $BUILD_ENV ${{ matrix.rocm-version }}
 
     - name: Install C/C++ Compilers
       run: . $PRELUDE; install_cxx_compiler $BUILD_ENV
@@ -102,73 +94,78 @@ jobs:
     - name: Install Build Tools
       run: . $PRELUDE; install_build_tools $BUILD_ENV
 
-    - name: Install PyTorch-ROCm Nightly
-      run:  . $PRELUDE; install_pytorch_pip $BUILD_ENV nightly rocm ${{ matrix.rocm-version }}
+    - name: Install CUDA
+      run: . $PRELUDE; install_cuda $BUILD_ENV ${{ matrix.cuda-version }}
+
+    # Install via PIP to avoid defaulting to the CPU variant if the GPU variant of the day is not ready
+    - name: Install PyTorch Nightly
+      run: . $PRELUDE; install_pytorch_pip $BUILD_ENV nightly cuda ${{ matrix.cuda-version }}
 
     - name: Collect PyTorch Environment Info
       if: ${{ success() || failure() }}
       run:  . $PRELUDE; collect_pytorch_env_info $BUILD_ENV
 
+    - name: Install cuDNN
+      run: . $PRELUDE; install_cudnn $BUILD_ENV "$(pwd)/build_only/cudnn" ${{ matrix.cuda-version }}
+
     - name: Prepare FBGEMM_GPU Build
       run: . $PRELUDE; cd fbgemm_gpu; prepare_fbgemm_gpu_build $BUILD_ENV
 
     - name: Build FBGEMM_GPU Wheel
-      run: . $PRELUDE; cd fbgemm_gpu; build_fbgemm_gpu_package $BUILD_ENV nightly rocm
+      run: . $PRELUDE; cd fbgemm_gpu; build_fbgemm_gpu_package $BUILD_ENV nightly cuda
 
     - name: Upload Built Wheel as GHA Artifact
       uses: actions/upload-artifact@v3
       with:
-        name: fbgemm_gpu_nightly_rocm_${{ matrix.host-machine.arch }}_${{ matrix.python-version }}_rocm${{ matrix.rocm-version }}.whl
-        path: fbgemm_gpu/dist/fbgemm_gpu_nightly_rocm-*.whl
+        name: fbgemm_gpu_nightly_cuda_${{ matrix.host-machine.arch }}_${{ matrix.python-version }}_cu${{ matrix.cuda-version }}.whl
+        path: fbgemm_gpu/dist/fbgemm_gpu_nightly-*.whl
 
 
   # Download the built artifact from GHA, test on GPU, and push to PyPI
   test_and_publish_artifact:
+    # runs-on: linux.4xlarge.nvidia.gpu
+    # Use available instance types - https://github.com/pytorch/test-infra/blob/main/.github/scale-config.yml
     runs-on: ${{ matrix.host-machine.instance }}
-    container:
-      image: "rocm/dev-ubuntu-20.04:${{ matrix.rocm-version }}-complete"
-      options: --user root --device=/dev/kfd --device=/dev/dri --ipc=host --shm-size 16G --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined
     defaults:
       run:
         shell: bash
     env:
       PRELUDE: .github/scripts/setup_env.bash
       BUILD_ENV: build_binary
-      ENFORCE_AMD_GPU: 1
+      ENFORCE_NVIDIA_GPU: 1
     strategy:
       fail-fast: false
       matrix:
         host-machine: [
-          { arch: x86, instance: "rocm" },
+          { arch: x86, instance: "linux.g5.4xlarge.nvidia.gpu" },
         ]
-        # ROCm machines are limited, so we only test against Python 3.11
-        python-version: [ "3.11" ]
-        rocm-version: [ "5.7" ]
+        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
+        cuda-version: [ "11.8.0", "12.1.1" ]
+        # Specify exactly ONE CUDA version for artifact publish
+        cuda-version-publish: [ "12.1.1" ]
     needs: build_artifact
 
     steps:
-    - name: Setup Build Container
-      run: |
-        apt update -y
-        apt install -y git wget
-        git config --global --add safe.directory '*'
-
+    # Cannot upgrade to actions/checkout@v4 yet because GLIBC on the instance is too old
     - name: Checkout the Repository
       uses: actions/checkout@v3
+      with:
+        submodules: true
 
     - name: Download Wheel Artifact from GHA
       uses: actions/download-artifact@v3
       with:
-        name: fbgemm_gpu_nightly_rocm_${{ matrix.host-machine.arch }}_${{ matrix.python-version }}_rocm${{ matrix.rocm-version }}.whl
+        name: fbgemm_gpu_nightly_cuda_${{ matrix.host-machine.arch }}_${{ matrix.python-version }}_cu${{ matrix.cuda-version }}.whl
+
+    # Use PyTorch test infrastructure action - https://github.com/pytorch/test-infra/blob/main/.github/actions/setup-nvidia/action.yml
+    - name: Install NVIDIA Drivers and NVIDIA-Docker Runtime
+      uses: pytorch/test-infra/.github/actions/setup-nvidia@main
 
     - name: Display System Info
-      run: . $PRELUDE; print_system_info
+      run: . $PRELUDE; print_system_info; print_ec2_info
 
     - name: Display GPU Info
       run: . $PRELUDE; print_gpu_info
-
-    - name: Free Disk Space
-      run: . $PRELUDE; free_disk_space
 
     - name: Setup Miniconda
       run: . $PRELUDE; setup_miniconda $HOME/miniconda
@@ -176,11 +173,12 @@ jobs:
     - name: Create Conda Environment
       run: . $PRELUDE; create_conda_environment $BUILD_ENV ${{ matrix.python-version }}
 
-    - name: Install Build Tools
-      run: . $PRELUDE; install_build_tools $BUILD_ENV
+    - name: Install CUDA
+      run: . $PRELUDE; install_cuda $BUILD_ENV ${{ matrix.cuda-version }}
 
-    - name: Install PyTorch-ROCm Nightly
-      run:  . $PRELUDE; install_pytorch_pip $BUILD_ENV nightly rocm ${{ matrix.rocm-version }}
+    # Install via PIP to avoid defaulting to the CPU variant if the GPU variant of the day is not ready
+    - name: Install PyTorch Nightly
+      run: . $PRELUDE; install_pytorch_pip $BUILD_ENV nightly cuda ${{ matrix.cuda-version }}
 
     - name: Collect PyTorch Environment Info
       if: ${{ success() || failure() }}
@@ -195,3 +193,9 @@ jobs:
     - name: Test with PyTest
       timeout-minutes: 15
       run: . $PRELUDE; cd fbgemm_gpu/test; run_fbgemm_gpu_tests $BUILD_ENV
+
+    - name: Push Wheel to PyPI
+      if: ${{ (github.event_name == 'schedule' && matrix.cuda-version == matrix.cuda-version-publish) || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_pypi == 'true' && matrix.cuda-version == matrix.cuda-version-publish) }}
+      env:
+        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
+      run: . $PRELUDE; publish_to_pypi $BUILD_ENV fbgemm_gpu_nightly-*.whl "$PYPI_TOKEN"
